### ISSUE TITLE
你好，请问一下阿里云集成waline不生效

### ISSUE THREAD

**Issue by ourlang** [BillSaul/blog#1]
![image](https://github.com/user-attachments/assets/3d5e1f99-c258-4d20-ad3a-c4c4b7d4ee0e)
![image](https://github.com/user-attachments/assets/552f5258-dc8b-4953-83f2-acaf1edf4292)
![image](https://github.com/user-attachments/assets/17bb374e-5aff-4c14-896a-bb5193e3493d)
![image](https://github.com/user-attachments/assets/099f5feb-1712-4fa2-b28e-f9aed9c1c997)

请问一下我这里哪里配置有问题吗，帮忙指导一下 谢谢
![image](https://github.com/user-attachments/assets/f289a2f7-388d-4a9d-9106-662ed0645805)

**Comment by BillSaul** [comment]
从你的图中来看，域名 `api.win1024.cn` 是你的 leancloud 数据库的访问域名。

如果你想把这个域名作为 waline 评论服务的域名，你应该按照[官方文档](https://waline.js.org/guide/get-started/#%E7%BB%91%E5%AE%9A%E5%9F%9F%E5%90%8D-%E5%8F%AF%E9%80%89)这样设置。

然后给 leancloud 数据库设置一个新的访问域名，例如：`leancloud.win1024.cn`。
